# Generated by Django 2.2.2 on 2019-06-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('idperson', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('idperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsistema.person')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('idpatient', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('cutes', models.IntegerField()),
                ('idperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsistema.person')),
            ],
        ),
        migrations.CreateModel(
            name='medicalvisit',
            fields=[
                ('idmedicalvisit', models.AutoField(primary_key=True, serialize=False)),
                ('comentary', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('idpatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsistema.patient')),
                ('idperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsistema.person')),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('iddoctor', models.AutoField(primary_key=True, serialize=False)),
                ('speciality', models.CharField(max_length=30)),
                ('idperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsistema.person')),
            ],
        ),
        migrations.CreateModel(
            name='cut',
            fields=[
                ('idcut', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('numbercut', models.IntegerField()),
                ('idmedicalvisit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emsistema.medicalvisit')),
            ],
        ),
    ]
