# Generated by Django 2.2.2 on 2019-06-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsistema', '0002_user_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='url',
            new_name='img',
        ),
    ]
